### ISSUE TITLE
Unable to create custom key bindings for opening files in splits and tabs

### ISSUE THREAD

**Issue by rbhanot4739** [junegunn/fzf.vim#764]
- Category
    - Question

- OS
    - Linux - Ubuntu 16.04 LTS

- Vim
    - Neovim - NVIM v0.3.2-208-g2841e89

Hello I am trying to map some of the key bindings to open the files in splits, and tabs and below is how my config looks.

```
let g:fzf_action = {
  \ 'a-t': 'tab split',
  \ 'a--': 'split',
  \ 'a-\': 'vsplit' }

```

Now when I try to launch `fzf` I get the below traceback of erros.

```
Error running ( /bin/zsh '/tmp/nvimMEazJM/5' )|'/spare/ssd/rbhanot/.confi...'-m' '--prompt' '~/' --expect=a-\,a--,a-t --no-height > /tmp/nvimMEazJM/4            
Error detected while processing function 306[24]..<SNR>66_exit_handler:                                                                                          
line    6:                                                                                                                                                       
error caught in async handler 'deoplete_on_event [{'rpc': 'deoplete_on_event', 'event': 'BufDelete', 'sources': []}]'                                            
Traceback (most recent call last):                                                                                                                               
  File "/spare/ssd/rbhanot/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 47, in on_event                                        
    self._deoplete.on_event(context)                                                                                                                             
  File "/spare/ssd/rbhanot/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 128, in on_event                                       
    self._context._init_cached()                                                                                                                                 
  File "/spare/ssd/rbhanot/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/context.py", line 78, in _init_cached                                     
    buftype = buffer.options['buftype']                                                                                                                          
  File "/apps/nttech/rbhanot/tools/miniconda3/envs/flask-env/lib/python3.7/site-packages/pynvim/api/common.py", line 88, in __getitem__                          
    return self._get(key)                                                                                                                                        
  File "/apps/nttech/rbhanot/tools/miniconda3/envs/flask-env/lib/python3.7/site-packages/pynvim/api/common.py", line 51, in request                              
    return self._session.request(name, self, *args, **kwargs)                                                                                                    
  File "/apps/nttech/rbhanot/tools/miniconda3/envs/flask-env/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request                               
    res = self._session.request(name, *args, **kwargs)                                                                                                           
  File "/apps/nttech/rbhanot/tools/miniconda3/envs/flask-env/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request                    
    raise self.error_wrapper(err)                                                                                                                                
pynvim.api.nvim.NvimError: b'Invalid buffer id' 
```

Am I missing something or doing something wrong here ?

**Comment by rbhanot4739** [comment]
Anyone any update?

**Comment by junegunn** [comment]
`a--` and `a-\` are not suppored by fzf. Check out `KEY BINDINGS` section of `man fzf` to see the list of supported key chords.
